import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { DatabaseSync } from "node:sqlite";
import { createHash } from "node:crypto";
import { CatalogStore } from "../src/server/catalog-store.ts";
import type { JobDraft, RunView, SourceDefinition } from "../src/shared/collection-contract.ts";
import { JOB_FIELDS } from "../src/shared/collection-contract.ts";
const source: SourceDefinition = { id: "fixture", company: "合成验收公司", name: "fixture", kind: "detail", entryUrl: "https://example.org/job", allowedUrls: ["https://example.org/job"], verifiedAt: "2026-09-20", note: "synthetic", companyRecord: { row: ["合成验收公司", "ai", "Agent", "", "", "", "https://example.org/job", "", "", "synthetic"], ownership: "private", aliases: [], firstSeenDate: "2026-09-20", channel: "online", channelEvidence: "https://example.org/job" } };
const run: RunView = { id: "run-test", input: { mode: "source_only", sourceIds: ["fixture"], requestId: "request-1", maxModelCalls: 0 }, state: "completed", startedAt: new Date().toISOString(), finishedAt: new Date().toISOString(), modelCalls: 0, documents: [], errors: [], candidates: 0, usage: { input: null, output: null }, preferenceRevision: 0 };
const job: JobDraft = { key: "fixture|https://example.org/job", sourceId: "fixture", company: source.company, url: source.entryUrl, applicationUrl: null, fields: Object.fromEntries(JOB_FIELDS.map(k => [k, null])) as JobDraft["fields"], assessment: { eligibility: "unknown", availability: "unknown", reasons: ["synthetic"], recommended: false }, firstSeenAt: run.startedAt, lastVerifiedAt: run.startedAt, extraction: "model", evidenceId: "evidence-1" };
job.fields.title = { quote: "synthetic", start: 0, end: 9 };
test("catalog v2 backs up v1; atomic acceptance, receipt replay, conflicts, reopen and interrupted recovery", async () => {
  const dir = await mkdtemp(join(tmpdir(), "xiaozhao-collection-db-")), backups = join(dir, "backups");
  await mkdir(backups);
  let catalog = new CatalogStore(join(dir, "catalog.db"));
  try {
    const original = catalog.snapshot();
    let updates = await catalog.collections(backups, [source]);
    const backupFiles = await readdir(backups); assert.equal(backupFiles.length, 1);
    const before = new DatabaseSync(join(backups, backupFiles[0]), { readOnly: true });
    assert.equal(before.prepare("PRAGMA user_version").get()?.user_version, 1); before.close();
    updates.saveRun(run);
    updates.saveEvidence(job.evidenceId, { sourceId: source.id, url: source.entryUrl, state: "readable", checkedAt: run.startedAt, text: "synthetic", hash: createHash("sha256").update("synthetic").digest("hex"), title: "synthetic", links: [], message: "", httpStatus: 200, requests: 2 });
    const candidate = updates.propose(run.id, job);
    assert.equal(candidate.kind, "new"); assert.equal(candidate.canAccept, true);
    assert.equal(updates.jobs().items.length, 0);
    assert.throws(() => updates.accept({ requestId: "accept-1", candidateIds: [candidate.id, "missing"], expectedRevision: 0, expectedCatalogRevision: original.revision }), /不存在/);
    assert.deepEqual(catalog.snapshot(), original); assert.equal(updates.jobs().items.length, 0);
    const input = { requestId: "accept-1", candidateIds: [candidate.id], expectedRevision: 0, expectedCatalogRevision: original.revision };
    const result = updates.accept(input);
    assert.equal(result.accepted, 1); assert.deepEqual(updates.accept(input), result);
    assert.throws(() => updates.accept({ ...input, candidateIds: ["different"] }), /重复/);
    assert.deepEqual(catalog.snapshot().companies.slice(0, -1), original.companies);
    assert.equal(catalog.snapshot().companies.at(-1)?.[0], source.company);
    assert.equal(updates.jobs().items.length, 1);
    assert.equal(updates.propose(run.id, { ...job, lastVerifiedAt: "2026-09-21T00:00:00Z" }).kind, "duplicate");
    assert.equal(updates.propose(run.id, { ...job, fields: { ...job.fields, title: { quote: "synthetic", start: 10, end: 19 } } }).kind, "duplicate");
    const tampered = updates.propose(run.id, { ...job, fields: { ...job.fields, salary: { quote: "invented", start: 0, end: 8 } } });
    assert.throws(() => updates.accept({ requestId: "invalid-evidence", candidateIds: [tampered.id], expectedRevision: result.revision, expectedCatalogRevision: catalog.snapshot().revision }), /证据/);
    assert.equal(updates.revision(), result.revision);
    const fresh = updates.evidence(job.evidenceId);
    updates.saveEvidence("old-evidence", { ...fresh, checkedAt: new Date(Date.now() - 90000000).toISOString() });
    const stale = updates.propose(run.id, { ...job, evidenceId: "old-evidence", assessment: { ...job.assessment, reasons: ["changed"] } });
    assert.throws(() => updates.accept({ requestId: "stale-evidence", candidateIds: [stale.id], expectedRevision: result.revision, expectedCatalogRevision: catalog.snapshot().revision }), /24 小时/);
    assert.equal(updates.revision(), result.revision);
    updates.saveRun({ ...run, id: "run-pending", input: { ...run.input, requestId: "request-2" }, state: "running", finishedAt: null });
    catalog.close(); catalog = new CatalogStore(join(dir, "catalog.db"));
    updates = await catalog.collections(backups, [source]);
    assert.equal(updates.run("run-pending").state, "interrupted");
    assert.equal(updates.jobs().items[0].firstSeenAt, job.firstSeenAt);
    assert.equal(catalog.integrity(), "ok"); assert.equal((await readdir(backups)).length, 1);
  } finally { catalog.close(); await rm(dir, { recursive: true, force: true }); }
});
