import type { CompanyRow } from './types.ts';
export const F = {n:0,cat:1,roles:2,city:3,code:4,alt:5,url:6,dl:7,dlTxt:8,note:9} as const;

export const CATS: [string, string][] = [
  ["net","互联网平台"],
  ["ai","AI 原生 · 大模型"],
  ["fin","金融科技 · 券商 · 量化"],
  ["soe","国企央企 · 运营商"],
  ["car","车企 · 智驾"],
  ["hw","硬件 · 机器人 · 芯片"],
  ["b2b","企业软件 · ToB"],
  ["game","游戏"],
  ["frn","外企 · 咨询"]
];
export const CATNAME = Object.fromEntries(CATS);

export const OWNERSHIPS: [string, string][] = [
  ["private","私企"],
  ["foreign","外企"],
  ["state","央国企"],
  ["public","科研/事业单位"]
];
export const OWNERSHIPNAME = Object.fromEntries(OWNERSHIPS);

export const RECRUIT_CHANNELS: [string, string][] = [
  ["online","线上可投"],
  ["hybrid","线上 + 线下"],
  ["offline","仅线下"],
  ["verify","待核验"]
];
export const RECRUIT_CHANNEL_NAME = Object.fromEntries(RECRUIT_CHANNELS);

// 只有官方公告明确写明现场收简历或线下投递时，才标记线下渠道。
// 搜索结果页不当作官方入口；直达官网、官方招聘系统、官方授权招聘页或官方邮箱统一视为线上可投。
export const HYBRID_RECRUIT_COMPANIES = new Set([
  "超聚变 xFusion","中国电子云（中电云计算）"
]);
export const HYBRID_RECRUIT_EVIDENCE = new Map([
  ["超聚变 xFusion","官网可投；2027 校招公告列明 9–10 月进校交流活动"],
  ["中国电子云（中电云计算）","官方校招简章明确：官网网申或宣讲会/双选会现场投递，二选一即可"]
]);
export const OFFLINE_ONLY_COMPANIES = new Set<string>([]);

// 默认按国内私企处理；外企、合资企业、央国企及事业单位在这里显式列出，避免影响原 DATA 结构。
export const FOREIGN_COMPANIES = new Set([
  "Apple 中国","NVIDIA 中国","Qualcomm 中国","微软亚太研发集团","亚马逊","SAP 中国研究院「STAR」",
  "埃森哲「AI 未来分析师计划 AAP」","凯捷 Capgemini","施耐德电气","西门子中国","GE 医疗 EEDP",
  "爱立信中国研发中心","IBM 中国","毕马威 KPMG","普华永道 PwC","Shopee 研发中心",
  "汇丰科技 HSBC","瑞银 UBS GTP","联发科 MTK","安谋科技 Arm China",
  "三星中国（西安 SRCX / 北京研究院）","博世 BCSC（无锡）","酷睿程 CARIZON"
]);
export const STATE_COMPANIES = new Set([
  "招银网络科技","中金所技术公司","上交所技术公司","浦银金融科技（浦发银行）","建信金科",
  "工行软件开发中心","农银金科","中银金科","交银金科","中信银行","江苏银行 总行金融科技培养生",
  "南京银行","宁波银行 总行金融科技定向生","徽商银行","兴业数金","中电金信","广发证券 IT",
  "中金公司","申万宏源","银河证券","招商证券","中信建投","华泰证券","中证股转科技",
  "国寿财险 金融科技中心","中国人保","中移金科","中原银行 / 郑州银行",
  "上海人工智能实验室","之江实验室","北京通用人工智能研究院 BIGAI","中科院计算所","启元实验室",
  "智源研究院「智星」","TeleAI（中国电信人工智能研究院）","紫金山实验室",
  "海康威视","京东方 BOE","紫光展锐","海光信息","长江存储","北京人形机器人创新中心",
  "长安汽车","广汽集团 / 研究院","上汽零束 / 上汽集团","德赛西威","一汽集团","东风研发总院",
  "中国汽研 CAERI","麒麟软件","锐捷网络",
  "达梦数据","超聚变 xFusion","中国电子云（中电云计算）","中移九天（中国移动数智事业部）",
  "中移互联网","咪咕 / 中国移动研究院 / 中移物联网","天翼云（中国电信）","联通数科","中科曙光",
  "浪潮集团","昆仑数智（中石油）","中电科 32 所","中电科智能科技研究院","中电科 58 所",
  "电科网安（中电科 30 所系）","中国网安 / 三十所","太极股份（中电科 15 所）","中核华辉",
  "国家电网（信通 / 国网智能）","南网数字集团（南方电网）","招商局集团","中国移动（集团统一）",
  "中国电信（集团）","中国联通（集团）","中国航信","北方华创","中景芯创"
]);
export const PUBLIC_RESEARCH_ORGS = new Set([
  "上海人工智能实验室","之江实验室","北京通用人工智能研究院 BIGAI","中科院计算所",
  "启元实验室","智源研究院「智星」","紫金山实验室"
]);
export function ownershipOf(row: CompanyRow){
  const name = row[F.n];
  if(FOREIGN_COMPANIES.has(name) || row[F.cat] === "frn") return "foreign";
  if(PUBLIC_RESEARCH_ORGS.has(name)) return "public";
  if(STATE_COMPANIES.has(name) || row[F.cat] === "soe") return "state";
  return "private";
}
export function classificationLabel(row: CompanyRow){
  const owner = OWNERSHIPNAME[ownershipOf(row)] || "";
  const category = (CATNAME[row[F.cat]] || "").split(" · ")[0];
  if((row[F.cat] === "frn" && owner === "外企") || (row[F.cat] === "soe" && owner === "央国企")) return owner;
  return owner + (category ? " · " + category : "");
}
export function recruitChannelOf(row: CompanyRow){
  if(ownershipOf(row) !== "state") return "none";
  const name = row[F.n];
  if(HYBRID_RECRUIT_COMPANIES.has(name)) return "hybrid";
  if(OFFLINE_ONLY_COMPANIES.has(name)) return "offline";
  const url = row[F.url] || "";
  if(/^mailto:/i.test(url)) return "online";
  if(/^https?:\/\//i.test(url) && !/bing\.com\/search/i.test(url)) return "online";
  return "verify";
}
export function recruitChannelEvidence(row: CompanyRow){
  const channel = recruitChannelOf(row);
  if(channel === "hybrid") return HYBRID_RECRUIT_EVIDENCE.get(row[F.n]) || "官方线上入口 + 官方公告确认的线下渠道";
  if(channel === "offline") return "官方公告仅见线下渠道";
  if(channel === "online") return /^mailto:/i.test(row[F.url] || "") ? "官方公告邮箱投递" : "官网或官方授权招聘系统可投";
  if(channel === "verify") return "当前仅保存了搜索页，需回公司官网核验";
  return "";
}

// [公司, 分类, 岗位/方向, 城市, 主码, 备用码说明, 入口, 截止(ISO或""), 截止显示, 备注]
export const DATA: CompanyRow[] = [
["腾讯","net","Agent 开发 · AI 全栈 · AI 应用","深圳/北京/上海","TECCED77Z1","备 7MFGOF99XU","https://join.qq.com/","","正式批进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["字节跳动","net","AI Agent · AI 应用 · 多模态","北京/上海/杭州","4THQCVV","备 VTRVDTB · 758T3HT · BJQVE55 · SWUQFDU；新码 4FGQH44","https://jobs.bytedance.com/campus","2026-12-31","至 12-31","勾选「正式」批；年底前约 2 次投递机会，别因为有新码重复投同一岗"],
["阿里巴巴（淘天/高德/钉钉/饿了么/盒马/夸克/通义）","net","AI Agent · AI 全栈 · AI 应用","杭州/北京","2T4KIB9F","备 2T4VLIMB · 2T4GF4IM；实习码 2T4HS9Q5 · 6GJN61F 别填","https://campus-talent.alibaba.com/campus/position?batchId=100000760001","","正式批","批次号必须是 100000760001；阿里系子业务同一系统，不用另找码"],
["阿里淘天 AI Studio","net","AI 应用研发 · Agent · RAG","杭州","1B3H3R","","https://campus-talent.alibaba.com/campus/position?campusShareCode=N5JJz6ukaesPOcQHnLvjvw_3KT2zHNSDIJ9hKKANCkk%3D&batchId=100000760001","","正式批","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["阿里云","net","AI Agent 研发 · AI 全栈 · Agent Infra · AI 应用","多地","1RJON2T","","https://campus-talent.alibaba.com/campus/position?batchId=100000760001","","毕业 2026-11~2027-10","一次投递 2 个意向且提交后不可修改，先想清第一志愿"],
["百度","net","AIDU · Agent 应用全栈 J99974","北京","IZH1JB","备 IZH1K1 · IS1JAH · IS133G；ISK63T 是实习链接","https://talent.baidu.com/jobs/list?recruitType=GRADUATE","","AIDU 提前批 + 正式批","AIDU 是专项冲刺；JD 写规划—执行—反思、多 Agent、RAG+Agent、成本时延评测"],
["拼多多","net","AI Agent 研发（优先）· 大模型 · AI Infra","上海","aj7XpWwVCq","大模型 Ggz2SaxtS4；正式批 W3FmE9gXeL；通用 d6j02mkPqq","https://careers.pddglobalhr.com/campus/grad?t=aj7XpWwVCq","","正式批 9 月","先投 AI Agent 研发；提前批码和正式批码分开"],
["京东（JDS / TGT）","net","AI Infra · 多模态大模型 · 全栈开发","北京","C927D","TET 管培生用 XIWC0P；旧码 C4Y35 · C4G1Y 是 26 届","https://campus.jd.com/","2026-11-30","08-17 ~ 11-30","TET 与 JDS/TGT 可同时申请，是两条线"],
["快手","net","可灵 · 大模型 · AI Infra","北京/杭州","campusXyZtJvC","快 Star 用 campusKkNBdvQph；备 WyDQqwGBt · campusgFjqZbPgn","https://campus.kuaishou.cn/","","进行中",""],
["蚂蚁集团（含 OceanBase）","fin","智能体平台 · AI 应用 · Java 后端","杭州/上海","不填码，点链接","阿里的码不能用在蚂蚁","https://u.alipay.cn/_1k7B5XFUsp4EWTJjqLBXDy","","进行中","链接本身就是内推入口，表单里别再填阿里码"],
["网商银行","fin","AI 应用 · Java","杭州","走蚂蚁内推链接","","https://hrrecommend.antgroup.com/guide.html?code=/G7GwF1XaegSmn6lxXkk/g1_NyQespxsKec3xznSOxI=","","提前批","和蚂蚁同一系统，投网商岗位用这条链接"],
["小红书","net","AI Agent · 大模型应用 · AI Coding","上海/北京/杭州","FBLHBZUNYCAD","T60AXDBN5XP8 更像实习 + 转正","https://job.xiaohongshu.com/link?referer_code=FBLHBZUNYCAD","","09-08 启动","⚠ 提交后不能补码，投前先定码；一次最多 5 志愿且可排序，是目前志愿最多的大厂"],
["美团","net","LongCat · AI 平台 · Java 后端","北京/上海","BZLWXC5","备 ANSJJZH","https://zhaopin.meituan.com/web/campus","2026-10-31","至 10-31","码能识别再用；头部里截止最早的一批"],
["B 站","net","AI 平台 · 大模型应用","上海","0A0N87","备 P17TMZ · EC16T7；旧码 T4K407 · 2X335Q 是 26 届/春招","https://jobs.bilibili.com/campus","","进行中","最多 2 志愿"],
["网易有道","net","AI Agent 应用开发 · AI 全栈（数据）· 算法应用","北京","无码","内推要员工发「邀请函」，没有公开口令","https://campus.163.com","","08-31 起招满即止，笔试 10-11","JD 直接写 RAG / Agent；网易互联网系统每人 1 志愿，别和互娱撞车"],
["网易互娱","game","游戏 AI · 后端","广州/上海","omqqNU","备 TIFh5R · fA169G · rDBXrQ · qPtwfi · Q5zose","https://game.campus.163.com","","进行中","网易系每人 1 志愿，和有道二选一"],
["网易雷火","game","LLM Agent · 游戏 AI Agent · Harness","杭州","走链接不算填码","另一条 introduceId=3cd70q6n5xv9eda9，两条任选一条","https://xiaozhao.leihuo.netease.com/neitui/#/?introduceId=v0hf3u68kxizxydc","2026-10-30","至 10-30","南开公告明列 Harness 方向；毕业范围 2026-09-01~2027-08-31"],
["得物","net","AI 应用 · 算法 · Java 后端","上海","4VPN5BZ","备 JABXADV（填在「大使推荐」栏）","https://campus.dewu.com/","","08-10 开","本轮确认是 27 届码；每人 2 次投递"],
["贝壳找房","net","家居 AI · 大模型应用 · Java","北京","IVVG3H","旧码 ISVG3S · IVKM9A 是 26 届","https://campus.ke.com/campus/jobs","","2027 秋招",""],
["SHEIN","net","AI 应用 · 算法","广州/南京","DSajZqyT","","https://careers.shein.cn/","","进行中","海外业务多，英文环境，澳洲背景加分"],
["Shopee 研发中心","net","Agent 开发工程师（常规批）· AI Star","深圳/上海/北京","DSybWVh7","备 NTAGK82","https://app.mokahr.com/su/jaxwma","2026-11-30","07-28 ~ 11-30","常规批 1 志愿 + AI Star 1 志愿各投一个；常规批里就有 Agent 开发工程师"],
["58 同城「58A 计划」","net","Agent 开发工程师 · 大语言模型 · AI Infra","北京","DSngZnU5","备 DSRTU4tZ · DScFZemh，三个都是 27 届","https://app.mokahr.com/m/campus_apply/58/150953?recommendCode=DSngZnU5","2026-11-01","09-01 ~ 11-01","岗位名就叫 Agent 开发工程师，是最直白的一个"],
["菜鸟","net","供应链 AI · Java 后端","杭州","2T4M03VB","备 2T4M03V4 · 1RMJRFH","https://campus-talent.alibaba.com/campus/position?batchId=100000760001","2026-10-05","08-05 ~ 10-05","投菜鸟岗用这个专属码；与阿里其他 BU 投递互不影响"],
["微博","net","大模型应用 · 推荐","北京","NTAMI1d","","https://career.sina.com.cn","","进行中","网申时填「内推码」栏"],
["唯品会","net","AI 应用 · 算法","广州","NTAArwH","","https://campus.vip.com/","2026-10-20","内推期 08-17 ~ 10-20","帖子写免简历筛"],
["高途","net","教育 AI 应用","北京","DS6yCBud","","https://app.mokahr.com/m/campusrecruitment/bjhl/102145?recommendCode=DS6yCBud&hash=%23%2Fjobs#/jobs","","进行中","链接自带码，直接投"],
["携程","net","Agent 开发工程师（2027 届秋招）","上海","NTAfGS2","旧码 NTAH5a6 是 26 届","https://www.nowcoder.com/jobs/detail/463573","","秋招每人 1 次","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["搜狐「引力计划」","net","AI 全栈研发 · AI 算法研发","北京/天津","DSCtTtZm","码出自南开 09-14 公告","https://app.mokahr.com/m/campus_apply/sohu/36036?recommendCode=DSCtTtZm#/jobs","","09-14 公告","每人 2 个岗位；AI 全栈优先于算法专项"],
["腾讯音乐 TME","net","AI 应用 · 后端","深圳/北京","DS8DMTYZ","备 DSBCNVWY","https://join.tencentmusic.com/campus/post","","进行中","官方 FAQ：没填码可在个人中心补填，但提交时用了 A 码就不能换 B 码；填码与否流程没差别，别为等码拖延"],
["滴滴","net","大模型应用 · 智能客服 Agent","北京/杭州","NTADaYM","备 DS5q4Y5d","https://outreach.didichuxing.com/elite/","2026-09-23","提前批至 09-23","提前批快关了，正式批以官网为准"],
["虎牙","net","AI 应用工程师 · 全栈 · 语音大模型","佛山/广州/深圳/武汉","NTABNaF","另一条 NTAGaDI 是往届别填；用下面的链接投可以不填码","https://app.mokahr.com/recommendation-apply/huya/4113?recommenderId=264905#/jobs?isCampusJob=1","2026-09-23","至 09-23","同时可投 2 岗；链接内推优先于填码"],
["爱奇艺","net","Java · 后端","北京","MQN4MKM","帖子写「长期有效」，表单认再填","https://iq.jobs.feishu.cn/s/i5yNhatK","","进行中","27 届主站校招公告没搜到，只有重庆客服岗"],
["顺丰科技","net","AI 开发 · AI 全栈 · 大模型算法","深圳/武汉/成都","无有效公开码","旧码 5UGFT7 · 01404691 都是 26 届，别填","https://campus.sf-express.com","2027-09-30","申请窗口到 2027-09","提前批 08-12 起，公告列 AI 开发/AI 全栈/大模型算法；先核对正式批当前职位"],
["阅文集团","net","技术岗（投递页有「AI 应用」附加题）","上海","无码","","https://join.yuewen.com/school","2026-10-31","09-14 ~ 10-31","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["去哪儿","net","AI 应用开发工程师（测试开发）· AI 产品运营","北京","无 27 届码","往届码一律别填","https://campus.qunar.com","2026-10-06","至 10-06","每人只能投 1 个岗"],
["货拉拉","net","后端开发（云原生 AI 平台 / 国际化 AI 项目）","深圳/北京/上海","无 27 届码","","https://www.bing.com/search?q=%E8%B4%A7%E6%8B%89%E6%8B%8927%E7%A7%8B%E6%8B%9B","2026-10-12","至 10-12","58 个岗，技术里有两个 AI 平台方向的后端"],
["哈啰","net","AI 全栈","上海","无 27 届码","旧码 MRA6K2 · NTAHPYm 是 26 届别填","https://careers.hellobike.com/","","进行中","有 AI 全栈岗，无码直投"],
["美图","net","AI Agent 研发","厦门/深圳","无码","","https://campus.meitu.com","","进行中","面向 2026-09 ~ 2027-12 毕业"],
["汽车之家「JIA STAR」","net","AI Agent 产品 / 研发","北京","无码","","https://www.bing.com/search?q=%E6%B1%BD%E8%BD%A6%E4%B9%8B%E5%AE%B6+JIA+STAR+2027%E6%A0%A1%E6%8B%9B","","进行中","27 届计划含 AI Agent 角色"],
["知乎","net","直答 Agent · 大模型应用","北京","无码","","https://app.mokahr.com/campus-recruitment/zhihu/68321#/","","进行中",""],
["作业帮","net","教育 Agent · 大模型应用","北京","无码","","https://app.mokahr.com/campus-recruitment/zuoyebang/150514?locale=zh-CN","","进行中",""],
["途虎养车","net","AI 应用 · Java","上海","无 27 届码","旧码 NTANZfX · DS11hsv9 是 26 届","https://campus.tuhu.cn","","09-08 开",""],
["途牛","net","AI 应用开发工程师 · 全栈","南京","无码","","https://www.bing.com/search?q=%E9%80%94%E7%89%9B+2027%E5%B1%8A%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","2026-10-21","至 10-21","自研 AI 助手「小牛」已上线；本科起，优先实习转正"],
["满帮集团","net","技术岗","贵阳/南京","无码","","https://campus.fulltruckalliance.com","","进行中",""],
["泡泡玛特","net","数字化与技术（算法 / AI / 后端）","北京","无码","","https://popmart.zhiye.com/campus","","进行中","2 志愿"],
["安踏集团","net","IT 产品 · 技术 · 商品智能化","厦门","无码","","https://campus.anta.com","2026-11-30","至 11-30","低优先"],
["蜜雪集团","net","系统开发 · 数据开发 · 信息安全","郑州","公告写不设内推码","","https://www.bing.com/search?q=%E8%9C%9C%E9%9B%AA%E9%9B%86%E5%9B%A2+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中","郑州本地岗，通勤成本最低，但是纯业务开发"],
["粉笔","net","NLP 算法工程师","北京","邮件直投","","mailto:lvhl@fenbi.com","","进行中","主题写「姓名+NLP算法工程师+校招」"],
["松鼠 AI","net","AI 算法 / AI 工程（明写 AI Agent）","上海","邮件直投","","mailto:qingsongwen@squirrelai.com","","进行中",""],
["阿里健康","net","技术岗","杭州","无码","和阿里主站码不通用","https://careers.alihealth.cn","2027-02-05","至 2027-02-05","独立招聘系统"],
["MiniMax","ai","Agent 产品 · 大模型应用","上海/北京/深圳","MJMNS4C","员工码可试 28BB6TD · NJ9YQ6J；4HFM3WU · M8GZTZ3 是实习/26 届补录别填","https://vrfi1sk8a0.jobs.feishu.cn/379481","2027-03-31","至 2027-03-31","⚠ 推荐方式必须选「大使推荐」，选「内推」会校验失败；2026-07~2027-03 最多投 3 次；旧分享链已 404"],
["智谱 Z.ai","ai","AutoGLM Agent · 评测算法 · 大模型工程","北京","NT7FWNH","备 ZQVBNUW（2026-03 帖）· QKTGW2S（2025 旧帖）","https://zhipu-ai.jobs.feishu.cn/s/t6UUWegpmwM","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["科大讯飞","ai","星火 Agent · AI 应用 · 飞星计划","合肥/北京/上海","EV3RHJ","飞星计划（27 届硕博 AI 研究算法）用 EVBRH0；备 EVVPSK · EV3RHG","https://iflytek.zhiye.com/5/jobs","","07 月起","飞星 / 飞凡两个计划，语音 NLP 多模态训练框架都在范围内"],
["DeepSeek","ai","大模型全栈 · 核心系统研发","杭州/北京","邮箱直投，无内推码","","https://talent.deepseek.com/","","常年开放","简历发 talent@deepseek.com，主题「姓名-岗位-联系方式」"],
["月之暗面 Moonshot","ai","大模型 · Agent 产品工程","北京","无码，走内推链接","","https://moonshot.jobs.feishu.cn/s/iFdosECp","","已开 2027/2028","官方校招页 careers.kimi.com/campus"],
["百川智能「源点计划」","ai","Agent 算法工程师","北京","E13K57R","届别没标，表单能识别再填","https://careers.baichuan-inc.com/origin-program","2026-12-31","全年开放，网申到 12-31","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["面壁智能「前进四」","ai","端侧大模型 · Agent","北京","邮箱直投","","mailto:career@modelbest.cn","","全年申请","硕士可投，邮件主题写岗位+学校+姓名"],
["实在智能","ai","Agent · RPA","杭州","邮箱直投","","mailto:campus@i-i.ai","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["星环科技","ai","智能体开发工程师 · 大模型算法 · AI 前线部署","上海/北京/南京/广州/成都","无公开码","官方只说「找在职学长学姐要码」","https://app.mokahr.com/campus_apply/transwarp","2026-12-31","08-18 ~ 12-31","研发类明列「智能体开发工程师」，窗口长、竞争小"],
["深势科技","ai","算法 · 大模型 · 工程开发","北京/上海/深圳","MZRPAQD","员工 2026-07 帖标 27 届","https://www.bing.com/search?q=%E6%B7%B1%E5%8A%BF%E7%A7%91%E6%8A%80+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中","官网「加入我们」→ 校园招聘（飞书系统）填码"],
["思必驰","ai","AI Agent 研发工程师","苏州","无公开码","","https://aispeech.zhiye.com/Campus","","09-07 公告","公告明确 27 届本科及以上、硕士优先；职责涉及多 Agent 调度、规划、记忆、工具编排。邮箱 xiaozhao@aispeech.com"],
["杉数科技","ai","AI Agent 研发工程师","北京/上海/广州","无公开码","","https://www.bing.com/search?q=%E6%9D%89%E6%95%B0%E7%A7%91%E6%8A%80+2027+AI+Agent+%E7%A0%94%E5%8F%91%E5%B7%A5%E7%A8%8B%E5%B8%88","","09-08 发布","职责含多智能体节点、RAG、上下文组装、动态工作流、成功率/Token/时延评估；需补运筹优化领域语义"],
["速境 Speediance","ai","大模型应用开发工程师","深圳","邮箱直投","","https://sil.speediance.com/zh/career","","进行中","career@speediance.com；投递时主动说明 2027-01 毕业"],
["海艺科技 SeaArt","ai","Agent 开发 · AI 应用 · AI 工程化","成都","无公开码","官网有内推入口但无码","https://app.mokahr.com/recommendation-apply/haiyi","2027-05-31","至 2027-05-31","可能招满提前关；「星海人才计划」是研究专项（Agentic RL / Harness），别和应用岗混投"],
["商汤科技","ai","日日新应用 · 行业 Agent","上海/深圳/北京","无 27 届码","","https://hr.sensetime.com/campus","","进行中","校招体系成熟，有专门的应用交付岗"],
["阶跃星辰 StepFun","ai","多模态 Agent · 终端智能","上海","无 27 届码","","https://www.bing.com/search?q=%E9%98%B6%E8%B7%83%E6%98%9F%E8%BE%B0+StepStar+2027%E6%A0%A1%E6%8B%9B","","进行中","有 Agent 岗，走公众号 / StepStar 计划"],
["依图科技","ai","算法工程师","上海","AA5ZR","自助内推链接，打开即带推荐人","https://app.mokahr.com/recommendation-apply/yitu-inc/3702?recommenderId=109456&hash=%23%2Fjobs%3FisCampusJob%3D1","","27 届正式批未开","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["云知声","ai","山海大模型 · 医疗 Agent","北京/厦门","无码","","https://unisound.zhiye.com/campus/jobs","","进行中",""],
["第四范式","ai","企业级 Agent · AIGS","北京","无 27 届码","2023 年的旧码别填","https://www.bing.com/search?q=%E7%AC%AC%E5%9B%9B%E8%8C%83%E5%BC%8F+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","待确认","企业 AI 落地老兵，工程规范强"],
["旷视 / 千里科技","ai","视觉 · 大模型","北京","无 27 届码","DSfnuT4Y 是 26 届别填","https://www.bing.com/search?q=%E6%97%B7%E8%A7%86%E7%A7%91%E6%8A%80+2027%E6%A0%A1%E6%8B%9B","","待确认",""],
["云天励飞","ai","芯片 · AI Infra","深圳","无码","","https://www.bing.com/search?q=%E4%BA%91%E5%A4%A9%E5%8A%B1%E9%A3%9E+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","27 届已开","偏芯片 / AI Infra"],
["晶泰科技","ai","AI for Science","深圳","邮箱争取内推","","mailto:career@xtalpi.com","","进行中",""],
["群核科技（酷家乐）","ai","科研算法 · AI Infra · AI 产品","杭州","无码","","https://www.bing.com/search?q=%E7%BE%A4%E6%A0%B8%E7%A7%91%E6%8A%80+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B","","招满即止","偏研究，走「群核科技招聘」公众号"],
["上海人工智能实验室","ai","多智能体 · 评测 · 书生浦语","上海","码要问员工或校园大使","","https://www.shlab.org.cn/joinus","","27 届已开","开源 Agent 框架（Lagent / XTuner）产出多，简历含金量高"],
["之江实验室","ai","研究 · 工程","杭州","无码","","https://talents.zhejianglab.com","","宣讲已排","偏硕博；邮箱 zhaopin@zhejianglab.org"],
["北京通用人工智能研究院 BIGAI","ai","研究工程师（智能体 / TongAgents）","北京","无码","","https://app.mokahr.com/campus-recruitment/bigai-ai/102640","","09-08 开","27 届全球校招，硕士起；提供住房与落户支持"],
["中科院计算所","ai","大模型训推 · NLP/RAG · AI 算法应用","北京","无码","","https://www.ict.ac.cn/rczp/","","常年招","解决北京户口；现在挂的是 2026 年度公告，27 届新公告约 10 月中"],
["启元实验室","ai","软件开发类研究及工程技术岗","北京","无码","","https://qiyuanzp.zhiye.com/","","常年","20–40K，硕士起；有政审，海外学历先问 HR"],
["智源研究院「智星」","ai","研究 / 工程","北京","无码","","https://www.bing.com/search?q=%E6%99%BA%E6%BA%90%E7%A0%94%E7%A9%B6%E9%99%A2+%E6%99%BA%E6%98%9F+2027","2026-09-26","07-28 ~ 09-26","公告要顶会或竞赛，没有就跳过"],
["字节 Seed 大模型人才校招","ai","Search Agent · Multi-Agent RL · 模型记忆系统","北京","用字节的码","和第一档字节同系统","https://seed.bytedance.com/zh/seedearlycareer","","进行中","研究型专项，作为冲刺"],
["米哈游","game","AI 技术中台 · 游戏 AI","上海","TTTGC","备 GZRRW；8UEZ 更像实习","https://jobs.mihoyo.com/","","提前批已开","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["沐瞳科技","game","Agentic 开发工程师 · AI 大模型研究","上海","48PWF6Z","备 FF42KAQ（链接 /s/pO9kcITv5Ng）· HYPRHKD，三选一","https://moonton.jobs.feishu.cn/s/A70Ws0XN7xo","","即日起","⚠ 投递前必填码，投后补不了；JD 含知识库、MCP、RAG、SFT/LoRA"],
["鹰角网络","game","游戏开发（Agent 研发方向）· AI 算法","上海","NTAcuvq","","https://career.hypergryph.com/","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["莉莉丝","game","2027 秋招算法工程师（Agent Harness / RAG）","上海","6G6T2FN","","https://lilithgames.jobs.feishu.cn/s/7N0IO3VJ1r8","","提前批","第三方 JD 写 Agent Harness、RAG、业务交付，硕博；回官网核实后再投"],
["叠纸游戏","game","游戏 AI · 后端","上海","9VZY3DV","校园大使码，技术岗能识别再填","https://career.papegames.com/s/E3xzfVBWDsg","2026-10-31","约 10-31",""],
["库洛游戏","game","技术岗","广州","KTBS4XE","美术早鸟码 BPBTBAJ 不适用技术岗","https://kurogame.jobs.feishu.cn/campus/","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["点点互动","game","AI Agent 工程师（Elite Program+）","北京/上海/深圳/广州","EV3P18","","https://ddhd.cn/4/jobs","","进行中","JD 含 AI 中台、LLM Agent 服务平台、工具调用、Eval；归在专项计划，不要当保底。08-31 免笔试权益已过期"],
["4399","game","AI Agent 技术开发岗","广州","9ueia","","https://hr.4399om.com/weixin/?r=job/agent&type=2&isOpen=0&jobTableType=1&code=9ueia","","进行中","不采信帖子的「直通笔试」承诺；链接里的 r=job/agent 不代表就是 AI 岗，要选中实际职位"],
["三七互娱","game","AI 中台 · 投放算法","广州/上海","DSC79bfC","偏 26 届 / 27 实习，核对届别","https://campus.37.com","","进行中",""],
["波克城市","game","算法 · 应用研发","上海","HSKNF84","","https://boke.jobs.feishu.cn/s/yj_x-yFzJPY","2026-10-18","08-18 ~ 10-18","投递时选「校园大使推荐」再填码"],
["西山居","game","技术岗","珠海/成都","NTAcp04","校招 / 实习 / 社招通用","https://www.bing.com/search?q=%E8%A5%BF%E5%B1%B1%E5%B1%85+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","招满即止",""],
["深蓝互动","game","游戏后端 · 算法","上海","NTAWufH","","https://www.bing.com/search?q=%E6%B7%B1%E8%93%9D%E4%BA%92%E5%8A%A8+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中","是上海游戏公司，不是长安深蓝汽车；方向偏，可放后"],
["巨人网络","game","AI 算法 · AI 工具","上海","NTAc9ft","","https://hr.ztgame.com/campus/","2026-09-30","员工内推到 09-30","官方 FAQ：近 3 个月已有投递会有保护期；先核对是否真有 AI 岗"],
["网龙","game","技术岗","福州","自助领码","关注「网龙集团招聘」公众号 → 我要外推 → 注册拿码；旧码 ESKG0K · EVKG39 是往届","https://nd.zhiye.com/campus/jobs","","进行中","少见的可以自助领内推码的公司"],
["心动 / TapTap","game","商业化算法 · 搜推算法（Agent 开发是实习转正岗）","上海","无 27 届码","AGqul（2021）· NTAGzXd（旧帖）别填","https://www.xd.com/hr","2026-09-25","08-28 ~ 09-25","⚠ 正式校招里没有 Agent 开发，那个是实习转正岗，别搞错"],
["完美世界","game","游戏 AI · 大模型应用","北京","找员工要码","","https://recruit.games.wanmei.com/","","进行中",""],
["小黑盒","game","AI 应用工程师","北京","无公开码","","https://job.xiaoheihe.cn","","进行中","只读到岗位清单，AI 岗具体职责未核实"],
["多益网络","game","2027 AI 应用开发工程师","广州","无公开码","","https://xz.duoyi.com/ANa","","进行中","毕业范围 2026-08 ~ 2027-07；先看应用开发，不要转投客户端凑数"],
["吉比特","game","技术岗","厦门","无码","","https://hr.g-bits.com","","进行中",""],
["乐元素","game","技术岗","北京","无码","","https://join.leyuansu.com","","进行中",""],
["小米","hw","端侧大模型 · 小爱 Agent · AI Agent 算法","北京/上海/西安","4Q6GKUB","备 QN8KF6Z","https://hr.xiaomi.com/campus","2026-12-31","至 12-31","AI Agent 算法岗（上海，硕士）含 LangGraph/MCP 也含 SFT 与后训练，属冲刺；AI 岗需求同比涨五成"],
["OPPO","hw","端侧大模型 · AI 手机 Agent","深圳/东莞","X6538748","","https://careers.oppo.com/university/oppo/campus/post","","07-15 起 · 招满即止","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["vivo","hw","蓝心大模型 · 端侧 Agent","深圳/杭州/南京","ES1CKS","","https://hr-campus.vivo.com/campus/jobs","2026-09-15","原件写 09-15 截止","⚠ 这个日期已经过了，先去官网确认是否还有补录或后续批次"],
["荣耀","hw","YOYO Agent · 端侧 AI","深圳","gmpsaa","","https://www.bing.com/search?q=%E8%8D%A3%E8%80%80+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","08-18 开","走「荣耀招聘」公众号投递流程填码"],
["大疆","hw","AI 算法 · 嵌入式 · 硬件研发","深圳","DSSAmMbW","备 DSuvNXaV · DSKeRdhz","https://apply.careers.dji.com/campus-recruitment/dji/143359","","进行中","也可走「拓疆者」计划"],
["传音控股","hw","端侧 AI · 海外 AI 应用","深圳","ESS43G","旧码 EVH89B 是 22–26 届别填","https://transsion.zhiye.com/4/jobs?shareId=50833d1c-a141-44bb-8bab-ef5548e6a932&shareSource=2","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["海康威视","hw","AI 应用 · 算法","杭州","9PPA31","备 36KAB4；U856E0 标 25–26 届，优先 9PPA31","http://campushr.hikvision.com","","进行中",""],
["大华股份","hw","AI 应用开发 · 大模型应用 · 多模态","杭州","605742","","https://job.dahuatech.com/","","进行中","⚠ 每人仅能投 1 个岗位，先选 AI 应用开发或大模型应用"],
["联想","hw","AI 软件 · 研发","北京","2027XZLMCWC","备 ANK2027 · 2027XZLMFWX · 2027XZLMZQY；26 届码 2026XZLMDWW 别填","https://talent.lenovo.com.cn/home","","进行中","部分公告要求填「推荐人 itcode」而不是一串码；简历保存和职位申请是两步"],
["韶音科技","hw","嵌入式 AI · 软件研发","深圳","DS1AT58B","","https://app.mokahr.com/m/campus-recruitment/aftershokzhr/36940","2026-10-30","提前批至 10-30",""],
["影石 Insta360","hw","AI 影像 · 应用工程","深圳","E45P9HR","校园大使码，技术岗能识别再填","https://www.bing.com/search?q=%E5%BD%B1%E7%9F%B3+Insta360+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中",""],
["石头科技","hw","算法 · 软件","北京","IS3Y19","","https://www.bing.com/search?q=%E7%9F%B3%E5%A4%B4%E7%A7%91%E6%8A%80+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中",""],
["追觅科技","hw","算法 · 软件","苏州","ISK0VJ","备 IV3CVA","https://www.bing.com/search?q=%E8%BF%BD%E8%A7%85%E7%A7%91%E6%8A%80+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中",""],
["云鲸智能","hw","RAG · 大模型开发","深圳","ISVYSK","年份没标；IS3GVR 是 24 届别填","https://careers.narwal.com","","进行中","27 届岗位里有 RAG / 大模型开发"],
["拓竹科技 Bambu Lab","hw","算法 · 软件 · 嵌入式 · 数据","深圳","9HZ64G6","","https://bambulab.jobs.feishu.cn/s/KQEJ6LJ8PDM","","进行中","消费级 3D 打印软硬件，软件/算法工程适配度高于纯大模型岗"],
["安克创新","hw","AI 数据 · 研发技术","深圳/长沙","N385CKS","","https://anker-in.jobs.feishu.cn/s/KF0dY1CMkHo","","进行中","公告列 AI 数据工程师，别当纯 Agent 岗；官网 career.anker.com.cn"],
["CVTE 视源","hw","算法 · 软件 · 研究类","广州","CVTEGZCWC","","https://campus.cvte.com/","","进行中","网申「招聘来源」选「内部推荐」后填码"],
["禾赛科技","hw","AI / 算法 · 软件 · 世界模型","上海","SUG1Z1V","","https://kwh0jtf778.jobs.feishu.cn/s/WMidFy4Ae6I","","进行中","偏物理 AI / 传感器，算法岗要 CV 或训练部署基础，属冲刺"],
["智元机器人 AgiBot","hw","Agent 算法 · 具身 Agent 算法","上海","XP9JUTE","备 1XD5CZ5","https://agirobot.jobs.feishu.cn/s/WIVzPj3j3IE","","进行中","帖子明列「Agent 算法工程师」「具身 Agent 算法工程师」"],
["银河通用 Galbot","hw","具身智能 · Agent","北京","D1KCYZC","链接自带码","https://owm6ymi5v9b.jobs.feishu.cn/584984/m/position?external_referral_code=D1KCYZC","","进行中",""],
["优必选","hw","人形机器人 · AI 软件","深圳","IVVJ30","届别自称 27，表单认再填","https://zhaopin.ubtrobot.com/campus","","进行中",""],
["自变量机器人","hw","具身算法 · 软件","深圳","FYNK8N8","","https://x2-robot.jobs.feishu.cn/s/URzjGh3o_wo","","招满即止",""],
["普渡科技","hw","Agent 开发工程师 · VLM · VLA","深圳/成都","无公开码","公告写「网申 / 内推」","https://pudutech.zhiye.com/campus","","招满即止","软件类明列 Agent 开发工程师"],
["极智嘉 Geek+","hw","Agent 工程师 · VLA · 强化学习 · 世界模型","北京/上海/苏州","无码","","https://www.geekplus.com/zh-cn/company/career","2026-10-21","至 10-21","笔试含 AI Coding"],
["星海图","hw","算法 · 大模型训练 · 仿真平台开发","北京/苏州/深圳","无码","","https://www.galaxeadynamics.com/career/2027campus","2026-10-27","至 10-27","中低优先"],
["穹彻智能","hw","具身 Agent 算法 · 世界模型 · Training Infra","上海","邮箱直投","","mailto:hr@noematrix.cn","2026-10-20","至 10-20","硕士；主题「姓名-意向岗位-学校」"],
["千寻智能","hw","具身 Agent 算法 · AI 平台研发 · 模型评测","北京/杭州/深圳","无码","","https://nwd4iy9rd2s.jobs.feishu.cn/campusofSpiritAI","","招满即止","campus@spirit-ai.com"],
["北京人形机器人创新中心","hw","多模态大模型算法（VLM / 世界模型）","北京通州","无码","","https://www.bing.com/search?q=%E5%8C%97%E4%BA%AC%E4%BA%BA%E5%BD%A2%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%88%9B%E6%96%B0%E4%B8%AD%E5%BF%83+2027%E6%A0%A1%E6%8B%9B","","进行中","硕士，25–50k×14；要 VLA/VLM 微调经验，顶会加分"],
["宇树科技 Unitree","hw","机器人软件 · 后端 · AI","杭州","无 27 届码","","https://www.unitree.com/cn/position","","进行中","热度高，投递人数也多"],
["寒武纪","hw","软件栈 · AI 编译 · 平台","北京/上海/西安","NTAtrFW","帖子写所有岗位通用","https://www.cambicon.com/campus/recruitment/2027campus","","进行中","软件类岗位多，不只招芯片"],
["摩尔线程","hw","GPU 软件栈 · AI Infra","北京/上海","无 27 届公开码","","https://www.bing.com/search?q=%E6%91%A9%E5%B0%94%E7%BA%BF%E7%A8%8B+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B","","进行中","可走知乎内推帖"],
["燧原科技","hw","AI 编译器 · 高性能算子 · 大模型算法","上海/北京","NTAsxIQ","备 NTAtGlE（内推人工号 901793）","https://app.mokahr.com/campus-recruitment/enflame/168420","","招满即止","郑州线上宣讲 09-19"],
["海光信息","hw","AI Infra · 软件","北京/成都","链接自带内推，不用填码","另有码 NTApcMK，链接优先","https://app.mokahr.com/su/11Pxti","2026-10-13","08-13 ~ 10-13",""],
["联发科 MTK","hw","嵌入式 · AI 软件","上海/北京/深圳","ISK60H","提前批码，正式批能识别再填","https://mediatek.zhiye.com/campus/jobs","","进行中",""],
["京东方 BOE","hw","应用解决方案 · 软件","北京/合肥","FY34V","","http://campus.boe.com","","进行中","⚠ 码只能首次网申时填，之后改不了"],
["紫光展锐","hw","AI 软件工程师","上海","无码","yocvoi 是 23 届别填","https://www.bing.com/search?q=%E7%B4%AB%E5%85%89%E5%B1%95%E9%94%90+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","2026-11-10","至 11-10","推理引擎 / AI 编译器 / Android 端大模型部署，偏底层，排在应用岗后"],
["沐曦","hw","GPU 软件 · AI","上海","无码","","https://www.bing.com/search?q=%E6%B2%90%E6%9B%A6+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中",""],
["昆仑芯","hw","AI 芯片软件","北京","无码","IZBG0B 是 26 届别填","https://www.bing.com/search?q=%E6%98%86%E4%BB%91%E8%8A%AF+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","27 届已开",""],
["长江存储","hw","软件 · 算法","武汉","填推荐人工号，无公开码","","https://ymtc-campus.zhiye.com/jobs","","进行中",""],
["安谋科技 Arm China","hw","软件开发岗","上海/北京","无码","","https://www.bing.com/search?q=%E5%AE%89%E9%9C%86%E7%A7%91%E6%8A%80+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","08-31 开","3 岗；偏芯片软件，放后"],
["TCL 华星","hw","算法 · 软件","深圳/武汉","wawoob","旧 svqejo；实业码 vvfoca 不能填华星","https://campus.tcl.com","","进行中","要选对招聘主体，别把实业和华星搞混"],
["TCL 实业","hw","AI 软件 · 应用","深圳/惠州","vvfoca","","https://zhaopin.tcl.com/campus","","进行中","与 TCL 华星是两个主体"],
["美的集团","hw","软件 · AI","佛山","M4Y642","","https://www.bing.com/search?q=%E7%BE%8E%E7%9A%84%E9%9B%86%E5%9B%A2+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中","走「美的招聘」公众号 → 伯乐推荐"],
["海尔集团","hw","软件 · 数字化","青岛","GHJ498","","https://www.bing.com/search?q=%E6%B5%B7%E5%B0%94%E9%9B%86%E5%9B%A2+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中","走「海尔招聘」→ 未来规划局推荐"],
["老板电器","hw","技术岗","杭州","找学长或校园大使要码","旧码 DScgmp49 · NTAfN14 是 26 届别填","https://campus.robam.com","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["普冉股份","hw","AI 应用开发工程师","上海","无公开码","","https://h2t8ckbsk1.jobs.feishu.cn/678396","","进行中","半导体企业里明确列出的 AI 应用岗；另有 Talent@puyasemi.com"],
["TP-LINK","hw","软件 · 算法","深圳","XYDS011","","http://hr.tp-link.com.cn/","","进行中","填「TP 内推码」栏"],
["三环集团","hw","软件","潮州","866001","","https://hr.cctc.cc/","","进行中",""],
["迈瑞医疗","hw","软件 · 算法","深圳","内推码 = 员工工号","","https://www.bing.com/search?q=%E8%BF%88%E7%91%9E%E5%8C%BB%E7%96%97+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中",""],
["联影集团","hw","医学影像 AI · 软件 / 算法","上海","IZV439","备 IZK6H9","https://www.bing.com/search?q=%E8%81%94%E5%BD%B1%E9%9B%86%E5%9B%A2+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中",""],
["三星中国（西安 SRCX / 北京研究院）","hw","多模态大模型算法 · AI 编译器","西安/北京","无码","","https://www.bing.com/search?q=%E8%A5%BF%E5%AE%89%E4%B8%89%E6%98%9F%E7%94%B5%E5%AD%90%E7%A0%94%E7%A9%B6%E6%89%80+27%E5%B1%8A%E6%A0%A1%E6%8B%9B","","9 月启动，岗位待放","岗位出来后在前程无忧搜「西安三星电子研究所」+ 27 届"],
["招银网络科技","fin","AI 研发 · Java 后端","深圳/杭州/成都","SFQSAK","","https://cmbnt.cmbchina.com/pages/bindInvited.html?qrCode=D164D34CEECC49399968E9607E743731&rand=1782916165724&blNtCode=SFQSAK","","27 秋招全球启动","⚠ 流程是先打开这条绑码链接、再去 career.cmbchina.com 网申；顺序反了码就丢。招行体系内最技术的一块"],
["恒生电子","fin","AI 应用开发 · 智能体开发 · 金融科技研发","杭州","EVSMAV","","https://campus.hundsun.com/campus/jobs?shareId=19851e61-6850-48fa-b21c-a1d6580dc2e6&shareSource=2","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["同花顺","fin","Agent 算法开发工程师（金融）","杭州","KV3275","帖子写面向 25/26/27 届；PR5578 是 26 届别填","https://campus.10jqka.com.cn/","","提前批已开","JD 明确写 Financial Agent Harness、Agent Loop、Skill/MCP、长程任务可靠性与评测——是金融线里最贴的一个"],
["度小满","fin","大模型 AI 应用开发 · AI 全栈研发 · AI 全栈（平台与数据）","北京/上海","QCU6N5T","","https://duxiaoman.jobs.feishu.cn/051736/m/position?external_referral_code=QCU6N5T","","毕业 2026-09~2027-08","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["众安保险","fin","AI 全栈工程师（2027 届秋招 - 上海）","上海","DSEbmnjv","校园大使码，正式批能识别再填；DSPjP563 出自旧帖别用","https://www.nowcoder.com/jobs/detail/465360","2026-11-30","09-04 ~ 11-30","JD：RAG、LangGraph、复杂 Agent 是加分项，核心是 AI 辅助前后端业务开发"],
["九坤投资「梧桐计划」","fin","AI 工程师（Agent 核心能力研究）","上海/北京","DStdWeNM","","https://app.mokahr.com/m/campus_apply/ubiquantrecruit/37031?recommendCode=DStdWeNM#/jobs","2026-09-30","提前批至 09-30","JD 写「Agent 核心能力研究」；也可邮件 recruiter@ubiquant.com，主题「姓名-岗位-校招」"],
["万得 Wind","fin","AI 工程 - 全栈开发 · AI 算法","上海/南京","sqh2027","26 届旧码 2026hwy1 别填","https://www.wind.com.cn/mobile/JoinUS/RecruitDetail/zh.html?entry=school","","招满即止","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["银泰商业","fin","银泰星 - AI 系统工程师 - 产技 J11330","杭州","ESKW1G","","http://talent.intime.com.cn/campus/jobs","","进行中","AI 系统建设、业务自动化与 Agent 实践；重点讲企业数据链路、部署、排障"],
["中金所技术公司","fin","大模型应用开发工程师","上海/苏州/北京","无码","","https://www.bing.com/search?q=%E4%B8%AD%E9%87%91%E6%89%80%E6%8A%80%E6%9C%AF%E5%85%AC%E5%8F%B8+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B+%E5%A4%A7%E6%A8%A1%E5%9E%8B","","招满即止","JD 要求熟练掌握 Agent、RAG、Java、前端，基于交易所 MaaS 平台做大模型应用；27 届硕士"],
["上交所技术公司","fin","研发岗（AI 中台 / AI 业务场景落地）","上海","无码","","https://www.bing.com/search?q=%E4%B8%8A%E4%BA%A4%E6%89%80%E6%8A%80%E6%9C%AF%E5%85%AC%E5%8F%B8+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","招满即止","交易所子公司，岗位稀缺"],
["浦银金融科技（浦发银行）","fin","AI 应用工程师 · AI 算法 · AI 治理","上海","无码","","https://www.bing.com/search?q=%E6%B5%A6%E5%8F%91%E9%94%B6%E8%A1%8C+2027+%E7%A7%8B%E5%AD%A3%E6%A0%A1%E6%8B%9B+%E6%B5%A6%E9%94%B6%E9%87%91%E7%A7%91","2026-10-08","10-08 18:00","岗位都在「人工智能应用中心」；AI 应用工程师本科起，毕业窗口 2025-01 ~ 2027-07"],
["阳光保险 科技条线","fin","AI 应用开发 · AI 应用算法 · AI 安全","北京/成都","SUNRISE2027","这是 27 届暑期实习专属码，校招表单能识别再填","http://sunzhaopin.sinosig.com/ygbxHr/","2026-10-08","09-10 ~ 10-08","公告强调「AI Native 思维」"],
["建信金科","fin","科技类专项岗","上海/北京","无码","","http://job.ccb.com","2026-10-08","至 10-08","27 届 30 人，2 志愿；走「诚聘英才」或「中国建设银行人才招聘」公众号"],
["工行软件开发中心","fin","大模型 · 算法研究 · 新技术研发","北京/珠海/成都等 7 城","官方无内推渠道","","https://job.icbc.com.cn","2026-10-08","至 10-08","搜「软件开发中心」；2 岗可选；笔试是硬关，提前刷题。工银科技 27 届未见公告，别混"],
["农银金科","fin","软件研发","北京","官方明确无任何内推","","https://career.abchina.com.cn","2026-10-08","至 10-08","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["中银金科","fin","信息科技岗","上海/北京/河北","官方无内推字段","","https://campus.chinahr.com/pages/2027-boc","2026-10-09","至 10-09","27 届 40 人，专业列了人工智能；全行 5 岗平行志愿"],
["交银金科","fin","人工智能 / 算法 · 后端","上海","无码","","https://www.bing.com/search?q=%E4%BA%A4%E9%80%9A%E9%94%B6%E8%A1%8C+2027+%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98+%E4%BA%A4%E9%94%B6%E9%87%91%E7%A7%91","2026-09-30","08-12 ~ 09-30","本月底截止，明列「人工智能/算法」岗，不认公开码，直接投"],
["中信银行","fin","信息科技","北京等","码只发员工","","https://job.citicbank.com","2026-10-09","至 10-09","最多 2 机构 × 2 岗；信银科技没搜到 27 届"],
["江苏银行 总行金融科技培养生","fin","软件开发 + 数据挖掘（大模型 / 智能信贷 / 智能投研）","南京","无码","","https://hr.jsbchina.cn/zp","2026-09-30","至 09-30","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["南京银行","fin","总行信息科技 · 数字银行；南银法巴消金「数字科技岗 - 人工智能方向」","南京/北京/上海/杭州","无码","","https://job.njcb.com.cn","2026-10-11","至 10-11","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["宁波银行 总行金融科技定向生","fin","算法 · 应用研发（后端/前端/数据）· SRE","宁波","无码","","https://zhaopin.nbcb.com.cn","2026-10-31","至 10-31","公开薪资 15–22K，本科起，免费三餐"],
["苏商银行","fin","AI 工程师（推动大模型业务场景落地）","南京河西","无码","","https://www.bing.com/search?q=%E8%8B%8F%E5%95%86%E9%93%B6%E8%A1%8C+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98+AI%E5%B7%A5%E7%A8%8B%E5%B8%88","","招满即止","总行入职 1V1 带教"],
["民生科技（民生银行）","fin","「扬帆」软件开发 · 数据智能算法","北京","无码","","https://www.bing.com/search?q=%E6%B0%91%E7%94%9F%E9%93%B6%E8%A1%8C+2027+%E7%A7%8B%E6%8B%9B+%E6%B0%91%E7%94%9F%E7%A7%91%E6%8A%80","","招满即止","JD 写大模型算法、提示词工程、Agent；硕士起"],
["徽商银行","fin","金融科技岗","合肥","无码","","https://rczp.hsbank.com.cn/pc/#/homepage","2026-10-08","至 10-08","低优先"],
["兴业数金","fin","金融 AI · Java","福州/上海","—","27 届提前批走 TouchCIB 科技挑战赛，报名已截止","https://www.bing.com/search?q=%E5%85%B4%E4%B8%9A%E6%95%B0%E9%87%91+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","正式批待开","等正式批公告"],
["微众银行","fin","AI 中台 · 大模型应用 · Java","深圳","无码","","https://campus.webank.com","","秋招正式批待开","27 届目前只发了实习招聘；技术导向最强的民营银行，值得盯"],
["平安集团 / 平安科技","fin","金融大模型 · Java 后端","深圳/上海","无 27 届公开码","","https://campus.pingan.com/","2026-11-06","08-10 ~ 11-06","最多投 3 家成员公司"],
["中电金信","fin","AI 智能体开发 · Java","北京","无码","","https://www.bing.com/search?q=%E4%B8%AD%E7%94%B5%E9%87%91%E4%BF%A1+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","27 届待开","26 届有 AI 智能体开发岗，10 月再看"],
["广发证券 IT","fin","Agent Infra 工程师 · AIOps · Java/Go/C++","广州","邮箱直投","","mailto:gfithr@gf.com.cn","","招满即止","JD 原文「算法造大脑，我们造四肢和神经」；硕士；流程含现场实习。邮件标题「岗位-姓名-学历-学校」"],
["中金公司","fin","信息技术","北京/上海/深圳","无码","","https://cicc.zhiye.com","2026-10-28","09-08 ~ 10-28","境内外院校都收，毕业不晚于 2027-10"],
["申万宏源","fin","金融科技","上海/北京/深圳","官方声明不接受任何付费内推","","https://www.bing.com/search?q=%E7%94%B3%E4%B8%87%E5%AE%8F%E6%BA%90+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B+%E9%87%91%E8%9E%8D%E7%A7%91%E6%8A%80","2026-10-25","至 10-25","硕士"],
["银河证券","fin","后端 · 数据 · 算法 · 运维 · 安全","北京","无码","","https://www.bing.com/search?q=%E9%92%B6%E6%B2%B3%E8%AF%81%E5%88%B8+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B+%E9%87%91%E8%9E%8D%E7%A7%91%E6%8A%80","2026-10-31","至 10-31","总部硕士优先"],
["招商证券","fin","金融科技岗","深圳/武汉","无码","","https://cms.hotjob.cn","","招满即止",""],
["中信建投","fin","金融科技类","北京","无码","","https://csc108.zhiye.com/campus/jobs","","招满即止","硕士"],
["华泰证券","fin","Fintech 专场","南京/上海","无码","","https://job.htsc.com.cn","","滚动招","27 届含 Fintech 专场"],
["中证股转科技","fin","北交所 / 新三板信息系统","北京金融街","无码","","http://zhaopin.neeq.com.cn","2026-09-30","至 09-30","硕士 ≤29 岁；每人 1 岗；有实习考察环节"],
["金证股份","fin","大模型应用开发工程师","深圳/长沙/上海/成都","无码","","https://www.bing.com/search?q=%E9%87%91%E8%AF%81%E8%82%A1%E4%BB%BD+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","2026-10-30","线下批 09-14 ~ 10-30","线上批 09-15 已过，走线下批或「金证招聘」公众号"],
["国寿财险 金融科技中心","fin","人工智能研发岗","北京","无码","","https://www.bing.com/search?q=%E4%B8%AD%E5%9B%BD%E4%BA%BA%E5%AF%BF+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98+%E8%B4%A2%E9%99%A9%E9%87%91%E8%9E%8D%E7%A7%91%E6%8A%80%E4%B8%AD%E5%BF%83","","招满即止","JD：大模型微调、大小模型协同、评测监控、Prompt 工程与知识库；解决北京户口"],
["泰康","fin","算法研发岗 - 27 校招","武汉光谷","无码","","https://www.bing.com/search?q=%E6%B3%B0%E5%BA%B7+2027%E6%A0%A1%E6%8B%9B+%E7%AE%97%E6%B3%95%E7%A0%94%E5%8F%91%E5%B2%97","","招满即止","垂类大模型 SFT / DPO、评测体系；16–35K；硕士"],
["中国人保","fin","科技类","北京等","无码","","https://www.bing.com/search?q=%E4%B8%AD%E5%9B%BD%E4%BA%BA%E4%BF%9D+2027%E5%B1%8A%E7%BB%9F%E7%AD%B9%E6%A0%A1%E6%8B%9B+%E7%A7%91%E6%8A%80%E7%B1%BB","2026-10-15","本级岗 10 月中旬","各单位批次 11 月中下旬"],
["汇丰科技 HSBC","fin","AI · 数据 · 云原生","广州/西安/上海","无码","","https://www.bing.com/search?q=HSBC+Technology+China+2027+campus+graduate","","9 月起","毕业 2025-07 ~ 2027-07；限中国籍"],
["瑞银 UBS GTP","fin","信息技术部管培生","上海","无码","","https://www.bing.com/search?q=UBS+Group+Technology+GTP+2027+China+campus","2026-10-31","08-17 ~ 10-31","面试新增 AI 熟练度考察"],
["衍复投资","fin","机器学习研究员 · Quantitative Developer","上海","无码","","https://yanfu.jobs.feishu.cn/index","2026-09-24","至 09-24","全职面向 2026–2027 届；邮件标题「2027衍复校招-姓名-岗位-全职」"],
["鸣石基金","fin","AI 量化工程师 · 量化开发（C++）","上海","无码","","https://mingshiim.zhiye.com/campus/jobs","2026-10-10","至 10-10","硕士起；也可 campus@mingshim.com，主题「姓名-学校-岗位」"],
["宽德投资「无境计划」","fin","机器学习平台 · ML 性能 · 策略系统","上海","邮箱直投","","mailto:hr@wizardquant.com","","招满即止","标题「2027校招无境计划+姓名+毕业院校+岗位名称」"],
["曹操出行","car","技术岗","杭州","DSdA9PrG","年份没标","https://www.bing.com/search?q=%E6%9B%B9%E6%93%8D%E5%87%BA%E8%A1%8C+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["理想汽车","car","智能空间 · AI 岗 ·「理想 +」","北京/上海","无公开码","南开页带渠道参数 H56UNDK","https://www.lixiang.com/employ/campus/list.html?fromJob=1","","即日起","27 届已开，AI 岗多"],
["小鹏汽车","car","AI / 智驾 · 大模型 ·「探索者计划」","广州/上海","CK45VF3","备 T8W2MCX · 3WGCND2；GWVHCUY 已失效","https://xiaopeng.jobs.feishu.cn/campus/?spread=T8W2MCX","","进行中","填在「人员推荐」栏；注意别误选博士专项"],
["蔚来","car","智能辅助驾驶 · 座舱 · 数智化 / AI 安全","上海/合肥","R6D4SHC","6WAVJHS 是实习码，不要用于正式校招","https://nio.jobs.feishu.cn/s/iPgS2LfV","","07-31 开",""],
["地平线","car","智驾大模型 · 工具链","北京/上海","exnxdy","fxfxgc · hlhvjk 是实习码别混用","https://horizon-campus.hotjob.cn/","","进行中","这是 27 正式校招码"],
["Momenta","car","智驾大模型 · 数据闭环","苏州/北京","HC8239D","是校园大使码，不是员工码","https://momenta.jobs.feishu.cn/s/_DFzXF7Dq9s","","进行中","官网投递时选「有内推」再填码；算法门槛高，平台/工具链岗相对友好"],
["小马智行 Pony.ai","car","AI 模型 · 世界模型 · 模型部署优化","北京/广州","935C7MU","","https://campus.pony.ai","","进行中","自动驾驶理论与 C++ 要求较高，作为冲刺"],
["文远知行 WeRide","car","算法 · 研发 · 测试开发","广州/北京/上海/深圳/武汉/新加坡","DSEenxY9","","https://app.mokahr.com/m/campus_apply/jingchi/2137?recommendCode=DSEenxY9#/jobs","","进行中","优先算法或平台研发"],
["轻舟智航 QCraft","car","算法 · 工程 · 产品项目","北京/苏州","4QS8UFY","","https://qcraft.jobs.feishu.cn/s/iFXv7aYm30E","","进行中","世界模型、强化学习、量产工程链路是主线"],
["九识智能 ZELOS","car","世界模型 · VLA · 数据闭环 · AI Infra","苏州","NTAXYvq","","https://app.mokahr.com/su/chahst","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["元戎启行","car","端到端智驾 · AI 工程","深圳","NTAW61d","备 NTAiLDj（链接 app.mokahr.com/su/etxxes）","https://app.mokahr.com/campus-recruitment/deeproute/145894#/","","进行中","先用 NTAW61d"],
["卓驭科技（大疆车载）","car","算法 · 软件（后端）","深圳","链接自带推荐人","牛客个人码 IZKA3B · IZ3A3J 未核实","https://we.zyt.com/5/jobs?shareId=394e07c9-41a3-467e-9bcd-ce7b445b8121&shareSource=2","","07-15 起",""],
["宁德时代","car","计算机 · AI 应用","宁德/福州/上海","DSFqvXqp","","https://app.mokahr.com/m/campus-recruitment/catlhr/148948?recommendCode=DSFqvXqp#/jobs","2027-12-31","毕业 2026-07 ~ 2027-12","官方说小红书会掉码，走上面这条网申链接；优先查计算机与 AI 类应用岗"],
["比亚迪","car","智能座舱 · AI 软件","深圳/西安","无 27 届码","BYDNTA05 是 26 春招别填","https://job.byd.com/","","进行中",""],
["吉利 / 极氪","car","座舱大模型 · AI","宁波/杭州/上海","公众号领码","关注「吉利招聘」公众号领","https://www.bing.com/search?q=%E5%90%89%E5%88%A9%E6%B1%BD%E8%BD%A6+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","2026-10-31","网申 / 内推到 10-31","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["长安汽车","car","智能化 · 软件","重庆","无码","阿维塔只有往届码","https://changan.zhiye.com/Campus","2026-09-29","09-01 ~ 09-29","本月底截止"],
["广汽集团 / 研究院","car","智能化 · 软件","广州","无码","","https://xyzp.51job.com/gacgroup2027","","09-09 起","集团 2 岗；研究院另有入口 gacrnd.zhiye.com"],
["上汽零束 / 上汽集团","car","软件 · 智能化","上海","无码","","https://www.bing.com/search?q=%E4%B8%8A%E6%B1%BD%E9%9B%86%E5%9B%A2+2027%E5%B1%8A%E5%85%A8%E7%90%83%E6%A0%A1%E6%8B%9B","","全球校招已开",""],
["德赛西威","car","软件类（AI 工程）· 算法专项","惠州/成都/上海/深圳/南京","无码","","https://www.bing.com/search?q=%E5%BE%B7%E8%B5%9B%E8%A5%BF%E5%A8%81+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","招满即止","毕业 2026-10 ~ 2027-10"],
["赛力斯","car","软件 & 算法 & 人工智能类","重庆","无码","","https://www.bing.com/search?q=%E8%B5%9B%E5%8A%9B%E6%96%AF%E9%9B%86%E5%9B%A2+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B","","招满即止","3 志愿；走「赛力斯集团微招聘」公众号"],
["一汽集团","car","智能网联研发 · 数智化","长春","无码","","http://zhaopin.faw.com.cn","","招满即止","1500 人，每个企业只能投 1 岗"],
["东风研发总院","car","AI 与大模型开发岗","武汉","无码","","https://www.bing.com/search?q=%E4%B8%9C%E9%A3%8E%E7%A0%94%E5%8F%91%E6%80%BB%E9%99%A2+2027%E6%A0%A1%E6%8B%9B+AI%E4%B8%8E%E5%A4%A7%E6%A8%A1%E5%9E%8B","","招满即止","东风股份另有入口 app.mokahr.com/campus-recruitment/gufen/143531"],
["易控智驾","car","平台研发 · 仿真与数据生成 · 智驾算法","郑州/北京","无公开码，找在职员工要","","https://www.eacon.com/join/","2026-10-28","至 10-28","矿区无人驾驶；郑州岗位；hrcampus@eacon.com"],
["酷睿程 CARIZON","car","深度学习 · 闭环算法 · HMI","北京/上海","无码","","https://www.bing.com/search?q=%E9%85%B7%E7%9D%BF%E7%A8%8B+CARIZON+2027%E6%A0%A1%E6%8B%9B","2026-11-30","至 11-30","大众 CARIAD 中国合资公司"],
["中国汽研 CAERI","car","数字化与 AI 算法类 · 智能网联","重庆/北京/苏州/郑州等","无码","","https://wecruit.hotjob.cn/SU6603d5a01eb8054100c60436/pb/index.html#/","2027-05-31","至 2027-05-31","国企；邮箱 hrm_zp@caeri.com.cn，主题「中国汽研+学校+学历+工作地点+专业」"],
["华为","net","盘古大模型 · AI 应用 · 车 BU 多模态","深圳/杭州/西安/上海","官方明确不设内推","FAQ 写只有天才少年走推荐，收费内推都是假的","https://career.huawei.com/cn/campus-recruitment","","进行中","车 BU 在「第一意向部门」选「智能汽车解决方案BU-智能驾驶解决方案产品线」；另有西安 AI 应用工程师岗需核实直签主体"],
["金蝶","b2b","Agent 开发工程师 · Harness 算法 · AI 开发","深圳/上海/南京/北京/长沙","67405","","https://app.mokahr.com/campus-recruitment/kingdeehr/166565?locale=zh-CN","","500 岗","毕业 2026-10 ~ 2027-09；JD 明列 Agent 开发 + Harness 算法，是全表岗位名最贴的一家。先看 Agent 开发，再判断 Harness 算法岗是否要训练经验"],
["用友网络","b2b","企业 Agent · YonGPT · 大模型算法 · 全栈","北京","RRbkY6Tn","27 届空宣码","http://career.yonyou.com","2026-11-30","网申到 11 月底","27 届算法类含大模型，研发类含全栈"],
["万兴科技","b2b","AI 应用开发工程师（Agent 应用与平台）J14851","长沙","IS3RT9","","https://www.nowcoder.com/jobs/detail/464164","","进行中","JD 明确涉及 Agent Harness、Skills、Memory、LangGraph、RAG、工作流与质量评估——重合度最高的几个之一。别把平台显示的 2029 投递区间当截止"],
["合合信息","b2b","Agent 开发 J14436 · AI 全栈 J14430 · 大模型应用算法 J14435","上海","IS3M9A","出自扫描全能王官方微博","https://intsig.zhiye.com/campus/jobs","2026-10-31","网申到 10-31","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["彩讯股份","b2b","AI 应用开发 · AI 全栈开发（智能体方向）","北京/广州/深圳/成都/杭州","无公开码","","https://www.richinfo.cn/jobs/","","进行中","公告明确写 Agent 编排、RAG、Skill 工具、多智能体、效果评测；邮箱 xiaozhao@richinfo.cn，标题「2027校招-渠道+城市+岗位+姓名+学历+院校+专业」"],
["广联达","b2b","AI Agent 开发工程师 · AI 数据开发（RAG 知识库）","北京/西安/上海","DSUQpag8","","https://app.mokahr.com/campus-recruitment/glodon/91966?recommendCode=DSUQpag8#/jobs","","提前批已开","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["博世 BCSC（无锡）","b2b","大模型算法工程师（Agent Harness）· AI 平台与 MLOps","无锡","NTAXJFp","备 NTAXieL · NTA6uhF（年份没标）；三个都不认就直投","https://jobs.smartrecruiters.com/BoschGroup/744000142551949--27-bcsc","","第一批 9 月中 Open Day","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["名创优品","b2b","AI 全栈创优生 · AI 解决方案创优生","广州","无公开码","官方说可找员工要","https://miniso.zhiye.com/campus","","即日起","JD 列 Agent、MCP、RAG、Milvus；不限投递数量，可以多投几个岗"],
["神州数码集团","b2b","Agent 开发 · AI 应用开发 · 多模态算法","北京/上海/深圳（共 16 城）","无码","和神州信息是两家公司","https://digitalchina.zhiye.com/campus/jobs","2026-11-02","至 11-02","AI 专项英才计划，AI 岗集中北上深"],
["中望软件","b2b","AI 应用开发工程师 · AI 算法工程师","武汉/广州/上海","无码","","https://www.zwsoft.cn/job/campus","","招满即止","共性技术研究院"],
["达梦数据","soe","Agent 开发工程师 · 算法工程师 · 数据库内核","武汉/成都/北京/上海/重庆/苏州","无码","","https://www.dameng.com/about/join.html","","招满即止","27 届明列「Agent 开发工程师」（15K+）；国产数据库头部，CEC 旗下国企背景"],
["超聚变 xFusion","soe","AI 软件开发工程师（MCP / 智能体平台 / AI 网关）","郑州/深圳/西安/北京/杭州","无公开码","","https://career.xfusion.com","","招满即止","JD 原文：企业级 AI 应用、智能体平台、MCP 工具、自动化工作流、AI 网关、鉴权、Token 计量、提示词模板。郑州总部 16 人，本科起；9–10 月进校活动已核验，是否现场收简历以场次通知为准"],
["中国电子云（中电云计算）","soe","Agent 开发 · AI Coding 开发 · LLM / 多模态算法","北京/武汉/南京/杭州/成都","无码","","https://campus.cestc.cn/campus-recruitment/cestc/102244","","招满即止","央企；毕业 2026-09 ~ 2027-07；南开公告另给邮箱 lichengrun@cestc.cn"],
["神州信息","fin","AI Agent 开发工程师 · AI 应用开发工程师","北京/上海/广州/深圳/西安/杭州","无码","官方只写「找在职师兄师姐」","https://dcits.zhiye.com/campus/jobs","2026-12-31","09-02 ~ 12-31","金融科技公司，JD 写 RAG 知识库、LangChain、ReAct；窗口到年底，从容投"],
["中移九天（中国移动数智事业部）","soe","AI 开发岗 · 算法开发岗 · 平台开发岗","北京/广东/陕西","无公开码","","https://job.10086.cn","2026-10-24","10-24 统一笔试","195 人，硕士起；产品含 MobileWork 办公智能体、AlphaData 智能体、九天大模型；境外学历要留服认证"],
["中移互联网","soe","AI 智能体开发 · AI 算法研发 · 后端","广州","无码","","http://zyhlw.hotjob.cn/","2026-10-24","随中移统一笔试","岗位名直接叫 AI 智能体开发"],
["中移金科","fin","AI 应用开发（行业智能体）· 算法（金融智能体）","北京","无码","","https://job.10086.cn","2026-10-24","随中移统一笔试","硕士；中国移动全资金融科技公司；在 job.10086.cn 选「中移金科」"],
["咪咕 / 中国移动研究院 / 中移物联网","soe","研发类 · 智能类 · 软件研发","北京/上海/杭州/成都/重庆","无码","","https://job.10086.cn","2026-10-25","10-24 ~ 25 笔试","研究院「智能类」技术含量最高"],
["天翼云（中国电信）","soe","后端开发（AI 方向为主）· 算法工程师 · 云计算研究员","北京/上海/广州/深圳/成都/厦门","lgyzmp","牛客个人帖码，能识别再填","https://ctyun.hotjob.cn","","招满即止",""],
["联通数科","soe","技术研发","北京/南京/西安/成都/深圳","无码","","https://ltsk.iguopin.com/","","招满即止",""],
["中科曙光","soe","AI Agent 研发 · 工业 Agent · 科学智能体","北京/天津","走内推入口即算内推","没有填码栏","https://neitui.italent.cn/sugon/candidate","","27 届已开","27 届有「AI Agent 研发工程师」「工业 Agent 研发」「科学智能体研发」三个方向"],
["浪潮集团","soe","AI 算力平台 · 软件开发","济南/北京","BNmxz5S","27 提前批码，正式批能识别再填","http://career.inspur.com/campus2027/index.html","","进行中",""],
["新华三 H3C","b2b","AI 算法工程师 · AI 调优工程师（Python）","杭州/北京","填推荐人工号 + 姓名","不是一串码；牛客有员工公开工号 28238（年份不明）","https://career.h3c.com/campus/jobs","","08-10 起","海外院校 2026-09 后毕业可投；网申后立刻做测评"],
["中兴通讯","b2b","AI 平台 · 星云大模型","深圳/南京/西安","无公开码","","https://job.zte.com.cn","","主批 08 月下旬已过","公众号回「内推」查进度；关注补录与春招"],
["昆仑数智（中石油）","soe","AI 算法（大模型 / 智能体 / 知识图谱）· AI 全栈工程师","北京","无码","","https://www.bing.com/search?q=%E6%98%86%E4%BB%91%E6%95%B0%E6%99%BA+2027+%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98+%E6%99%BA%E8%83%BD%E4%BD%93","2026-10-15","09-09 ~ 10-15","硕士；每人最多 2 家单位 × 1 岗；公告写北京生源优先；留学生要留服认证"],
["中电科 32 所","soe","AI 应用开发工程师 · Java 开发","上海","邮箱直投","","mailto:hr_zp@ecict.com.cn","2026-09-30","08-31 ~ 09-30","事业编；本月底截止，不认公开码"],
["中电科智能科技研究院","soe","软件开发工程师（专业列人工智能）","北京","邮箱直投","","mailto:cetc_znyhr@cetc.com.cn","2026-10-26","至 10-26","简历命名「2027届+姓名+毕业院校+专业+学历+拟投递岗位」"],
["中电科 58 所","soe","AI 算法 · AI 编译器","无锡/南京/武汉/西安/成都","无码","","https://www.bing.com/search?q=%E4%B8%AD%E7%94%B5%E7%A7%9158%E6%89%80+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B","2026-12-31","至 12-31",""],
["电科网安（中电科 30 所系）","soe","AI 算法工程师 · AI 攻防安全研究","成都/北京/武汉","无码","","https://www.bing.com/search?q=%E7%94%B5%E7%A7%91%E7%BD%91%E5%AE%89+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B","2026-09-21","网申到 09-21","这周就截止；国企，海外学历投前先问政审"],
["中国网安 / 三十所","soe","人工智能安全研究员 · Java / C++","成都","无码","","https://app.mokahr.com/campus_apply/cetc30/36270","2026-09-25","至 09-25","硕士；有安家费"],
["卡奥斯 COSMOPlat（海尔）","b2b","FDE（AI 原生应用端到端交付）· 工业智能体 · AI 算法","青岛/北京/上海","无码","","https://maker.haier.net/client/campus/customizedptjobs/id/87.html","2026-11-02","至 11-02","FDE 类就是 AI 原生应用全链路开发交付，本科起；也可走「卡奥斯招聘」公众号"],
["先导智能","b2b","AI 应用开发工程师 J17813","广州/无锡","无码","","https://leadchina.zhiye.com/campus","","09-10 公告","JD：LLM 接口、RAG、模型路由、Token 统计、MES/SCM 集成；邮箱 campus@leadintelligent.com，限 3 岗"],
["麒麟软件","b2b","AI 研发工程师（应用分支）","北京/天津/长沙","无公开码","","https://kylinos.zhiye.com/campus/detail?jobAdId=dd5441a9-cf8e-4b07-9a08-5bcf2db1e11a","","09-04 发布","OS AI 助手、Agent/RAG、工具调用、记忆；同一 JD 也含模型量化和算子，别把自己包装成推理优化专家"],
["达观 / 中控信息","b2b","AI 应用工程师","杭州","无 27 届码","NTAWcqw 是 26 届别填","https://www.bing.com/search?q=%E4%B8%AD%E6%8E%A7%E4%BF%A1%E6%81%AF+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98+AI%E5%BA%94%E7%94%A8%E5%B7%A5%E7%A8%8B%E5%B8%88","","进行中","JD 含 Agent 与算法平台集成、AI 编程及 Java 微服务；注意浙江中控信息与中控技术不是同一招聘主体"],
["帆软","b2b","Agent 研发工程师","南京/无锡/成都","正式批无可用码","提前批码 NDPGP · BLGLY · FDYHC 均已过期（08-31 截止）","https://join.fanruan.com/campus/","","正式批进行中","AI+BI 场景；具体 Agent JD 需回官网核实，别默认是 RAG 岗"],
["深信服","b2b","安全 GPT · 平台后端","深圳","NTAN7JQ","备 NTAKS7a · NTAF5rh；页面没写届别","https://hr.sangfor.com","","进行中","校招培养体系口碑好，技术训练扎实"],
["奇安信","b2b","安全大模型 · Agent","北京","无 27 届码","","https://campus.qianxin.com/campus/intern","","进行中",""],
["绿盟科技","b2b","安全 · AI","北京","NTAcaii","出自搜索摘要，来源页未打开","https://www.bing.com/search?q=%E7%BB%BF%E7%9B%9F%E7%A7%91%E6%8A%80+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B","","技术岗公告未出","目前只见校园大使招聘；安全公司 AI 岗少，低优先"],
["长亭科技","b2b","AI 研发工程师 · Agent 相关方向","北京","无 27 届码","NTAPiHV 是 26 届别填","https://campus2027.chaitin.cn/","2027-12-31","毕业 2026-09 ~ 2027-12","官方 27 届 AI 人才校招专题；「星柳」顶尖专项是攻防研究，别混投。resume@chaitin.com"],
["亚信安全","b2b","大模型开发 · AI 研究与架构 · 算法","南京/北京","V2NRKVF","","https://asiainfo-sec.jobs.feishu.cn/s/wxf-PC9cvy8","","进行中","先看大模型开发是否做知识库 / Agent / 业务集成；帖子的「免笔试」未验证"],
["迪普科技","b2b","AI 应用开发 · 网络安全 · C / Java 研发","杭州","3PU7XFJS","备 RK2THY42","http://zhaopin.dptech.com/","","进行中","原帖明确列有 AI 应用开发"],
["汇川技术","b2b","AI 算法 · 机器人算法 · C++ / 应用软件","深圳/苏州","RM48KWC","IZ373H · ISV4B3 · IZV1H0 都是 26 届或更早，别填","https://recruit.inovance.com","","进行中","3 志愿；工业方向，中低优先"],
["三一集团","b2b","AI 应用工程师","长沙","ESKMBS","旧码 25318 已报无效；ESKM89 线索未核实","https://sanycampus.zhiye.com/campus/jobs?shareId=0f1f4dfe-9eb1-4d80-9a35-8d8b4d42d392&shareSource=2","","进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["树根互联（三一系）","b2b","AI 全栈开发工程师（AI Coding 前后端）","广州/长沙","邮箱直投","","mailto:lina.jiang@irootech.com","","招满即止","要求可实习 3 个月到岗，转正性质"],
["新大陆科技集团","b2b","算法（大模型 / 视觉 / AI）","福州","无可靠 27 码","","https://newland.zhiye.com","","09-14 公告","优先大模型应用 / 检索工程分支；邮箱 hrxz@newland.com.cn"],
["东软集团","b2b","人工智能工程师 · 算法工程师","沈阳/大连/上海","无可靠 27 码","","https://neusoft-campus.zhiye.com/","","进行中","硕士及以上；问清产品研发 / 项目交付 / 驻场和劳动合同主体"],
["杰瑞集团","b2b","27 届 AI 开发工程师 - 成都","成都","无公开码","","https://jereh.zhiye.com/campus","","需确认","在系统里搜「27届-AI开发工程师-成都」确认还开放再投；提前批 08-30 已结束，别回投。不投博士专属计划"],
["华大基因","b2b","AI 技术方向储备生（AI 应用开发）","深圳","无码","","https://genomics.zhiye.com/campus","","即日起","AI 应用开发、生物数据处理、智能系统构建"],
["卫宁健康","b2b","AI 应用工程师 - 27 届 · 算法（大模型工程）","上海等","无码","","https://www.bing.com/search?q=%E5%8D%AB%E5%AE%81%E5%81%A5%E5%BA%B7+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B+AI%E5%BA%94%E7%94%A8%E5%B7%A5%E7%A8%8B%E5%B8%88","","招满即止","本科、专业不限；LLM 基础 + NLP / 对话系统项目加分"],
["数坤科技","ai","大模型算法工程师","北京/上海","无码","","https://www.bing.com/search?q=%E6%95%B0%E5%9D%A4%E7%A7%91%E6%8A%80+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","2026-10-19","至 10-19","医疗 AI 大模型；走公众号「数坤科技」→ 加入我们"],
["声网 Agora","b2b","对话式 AI · RTC","上海","无码","","https://www.shengwang.cn/about/jobs","","岗位已发","实时对话 Agent（语音打断、低延迟）技术点很硬"],
["软通动力","b2b","AI 应用开发","北京/西安/成都","无码","","https://www.bing.com/search?q=%E8%BD%AF%E9%80%9A%E5%8A%A8%E5%8A%9B+2027%E5%B1%8A%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","2027-12-31","毕业 2027 全年","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["中软国际","b2b","AI 应用开发","北京/杭州/大连","无码","","https://www.bing.com/search?q=%E4%B8%AD%E8%BD%AF%E5%9B%BD%E9%99%85+2027%E5%B1%8A%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","招满即止","保底选项"],
["汉得信息","b2b","咨询顾问 - AI 方向 · Java 后端","上海/武汉","无码","","https://www.bing.com/search?q=%E6%B1%89%E5%BE%97%E4%BF%A1%E6%81%AF+2027%E7%A7%8B%E6%8B%9B","2026-09-25","至 09-25","保底"],
["金山办公","b2b","技术岗","珠海/北京","无 27 届码","NTA7mnS 是 26 届","https://join.wps.cn","","进行中",""],
["360","b2b","技术岗","北京","无 27 届码","IZVM0T 是 26 届","https://360campus.zhiye.com","","进行中",""],
["明源云","b2b","产研岗（后端 / 测试，后续滚动开）","深圳","无码","","https://www.bing.com/search?q=%E6%98%8E%E6%BA%90%E4%BA%91+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B","2026-10-06","09-08 ~ 10-06","现在只有顾问 / 产品岗，产研岗后续开；地产 SaaS，低优先"],
["锐捷网络","b2b","软件研发","福州","DSEzRFug","","https://www.bing.com/search?q=%E9%94%90%E6%8D%B7%E7%BD%91%E7%BB%9C+2027%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","进行中","偏 27 实习转正"],
["太极股份（中电科 15 所）","soe","Java 开发工程师","北京/重庆","无码","","https://www.bing.com/search?q=%E5%A4%AA%E6%9E%81%E8%82%A1%E4%BB%BD+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B","","招满即止","硕士；保底"],
["中核华辉","soe","AI 研发工程师（全栈）","北京","无码","","https://www.bing.com/search?q=%E4%B8%AD%E6%A0%B8%E5%8D%8E%E8%BE%89+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B+AI%E7%A0%94%E5%8F%91%E5%B7%A5%E7%A8%8B%E5%B8%88","","招满即止","Python / Java / TypeScript，要 AI 应用项目交付经验；硕士"],
["国家电网（信通 / 国网智能）","soe","人工智能类 · 平台研发","多地","无码","官方明确不设内推","https://zhaopin.sgcc.com.cn","2026-11-15","第一批 11 月中旬","笔试预计 12 月上旬；留学生要上传留服认证"],
["南网数字集团（南方电网）","soe","专业含人工智能","广州/深圳等 8 城","无码","","https://www.bing.com/search?q=%E5%8D%97%E7%BD%91%E6%95%B0%E5%AD%97%E9%9B%86%E5%9B%A2+2027%E5%B1%8A%E6%A0%A1%E6%8B%9B","2026-09-30","提前批 9 月内","约 160 人，硕士；正式批随后"],
["招商局集团","soe","技术类","深圳","无码","","https://cmhk.zhiye.com","","09-09 启动",""],
["金山云「云翼计划」","b2b","管培生（AI 课题实战）","珠海","无码","","https://job.ksyun.com/campus/apply?source=campus&positionId=135669","2026-10-31","至 10-31","低优先；金山系上市公司，不归入央国企"],
["中国移动（集团统一）","soe","技术类 · 智能类","全国","官方明确无内推","","https://job.10086.cn","2026-10-24","统一笔试 10-24",""],
["中国电信（集团）","soe","技术类","全国","官方明确无内推","","https://www.bing.com/search?q=%E4%B8%AD%E5%9B%BD%E7%94%B5%E4%BF%A1+2027%E5%B1%8A%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98","","9 月启动",""],
["TeleAI（中国电信人工智能研究院）","ai","研究员（具身 / 世界模型 / AI Infra / AI 安全）","上海/北京","无码","","mailto:TeleAI.HR@Chinatelecom.cn","","招满即止","偏研究、偏顶会；标题「姓名 + TeleAI Top Talent + 意向方向 + 城市」。中低优先"],
["中国联通（集团）","soe","技术类","全国","官方明确无内推","","https://hr.chinaunicom.com","","9 月启动",""],
["Apple 中国","frn","机器学习与人工智能类 · 软件和服务类","上海/北京/深圳/苏州","无码","","https://jobs.apple.com/zh-cn/search?location=china-CHNC","2026-11-30","9 月投递","本硕可投，筛「学生 / 应届」"],
["NVIDIA 中国","frn","应届生技术岗","上海/北京/深圳","无码","","https://www.bing.com/search?q=NVIDIA+China+2027+new+grad+campus","","已发布",""],
["Qualcomm 中国","frn","应届生技术岗","上海/北京/深圳","无码","","https://www.bing.com/search?q=Qualcomm+China+2027+campus+new+grad","","已发布",""],
["微软亚太研发集团","frn","软件工程师","北京/苏州","员工邮件内推需 Job ID","无公开码","https://www.microsoft.com/zh-cn/aprd/recruitment","","进行中",""],
["亚马逊","frn","SDE","北京/上海/深圳","员工邮件内推","无公开码","https://www.bing.com/search?q=amazon.jobs+china+2027+new+grad+SDE","2026-10-24","约 08-24 ~ 10-24","每人最多 3 岗"],
["SAP 中国研究院「STAR」","frn","Generative AI Developer","上海/西安","找员工内推","","https://www.bing.com/search?q=SAP+China+STAR+program+2027+campus","","进行中",""],
["埃森哲「AI 未来分析师计划 AAP」","frn","人工智能 · 算法 · 研发","上海/北京/大连","无码","","https://www.accenture.com/cn-zh/college-internship","2026-11-08","09-08 ~ 11-08","毕业 2026-01 ~ 2027-08"],
["凯捷 Capgemini","frn","AIGC 开发工程师 · AI 开发工程师","大连/沈阳/上海/北京","无码","","https://www.bing.com/search?q=Capgemini+China+2027+campus+AIGC","","招满即止","JD 写「了解 RAG / 微调 / 私有部署优先」；保底"],
["施耐德电气","frn","技术咨询和 AI 应用顾问 · 研发新星","北京/上海/广州","无码","","https://www.bing.com/search?q=%E6%96%BD%E8%80%90%E5%BE%B7%E7%94%B5%E6%B0%94+2027%E7%A7%8B%E6%8B%9B","2026-09-17","网申 09-17 截止","2 个平行志愿，投完不能改；走「施耐德电气招聘」公众号"],
["西门子中国","frn","SCM Specialist (Digital & AI)","北京","员工内推","","https://jobs.siemens.com/zh_CN/externaljobs/JobDetail/521819","","进行中","硕士应届，要机器学习 + Python"],
["GE 医疗 EEDP","frn","研发培训生（软件与计算机工程）","北京/天津/无锡","无码","","https://www.bing.com/search?q=GE+HealthCare+China+EEDP+2027+campus","","08-31 起","硕士，2 年轮岗，Java / C++ / Python"],
["爱立信中国研发中心","frn","5G / 6G / AI Software Developer","北京/成都","无码","","https://www.bing.com/search?q=Ericsson+China+2027+campus+software+developer","2027-12-31","毕业 2026-01 ~ 2027-12",""],
["IBM 中国","frn","通用校招","北京/上海/大连","无码","","https://www.ibm.com/cn-zh/careers","","预计 10 月",""],
["毕马威 KPMG","frn","科技研发线（软件工程师 - AI 工程方向）","大连/上海","无码","","https://www.bing.com/search?q=KPMG+China+2027+%E7%A7%8B%E6%8B%9B+%E7%A7%91%E6%8A%80","","08-07 起","保底"],
["普华永道 PwC","frn","科技咨询","上海/北京","无码","","https://www.bing.com/search?q=PwC+China+2027+campus+technology","","秋季入职批","接 2025-08 ~ 2027-08 毕业；保底"],
["紫金山实验室","ai","网络大模型 · 网络智能体","南京","无码","","https://xy.liepin.com/pmlabs/","","27 届未发","26 届是 09-11 ~ 11-10，10 月再看；hr_zhaopin@pmlabs.com.cn"],
["中原银行 / 郑州银行","fin","算法工程师（大模型 / 知识工程）","郑州","无码","","https://zybank.zhiye.com/campus/jobs","","27 届待出","26 届是 09-22 发、10-31 截止，按惯例这两周出公告；郑州本地"],
["中国航信","soe","人工智能助理研究员 · 算法工程师","北京 + 17 城","无码","","https://travelsky.hotjob.cn","","27 届待出","26 届 09-25 开、11-25 截止；解决北京户口、六险二金；每单位 1 岗"],

// ---- 每日追加区：新公司只能追加到这里，禁止插入或重排上方历史数据 ----
["途游游戏","game","游戏 AI 算法工程师 · AI 游戏开发","北京","DS6wt6FY","备 DSgFzmFQ；两条均来自公开 27 届内推帖，未在表单实测","https://app.mokahr.com/campus_apply/tuyoogame/146219?recommendCode=DS6wt6FY#/jobs","","27 届进行中","岗位涉及 LLM、多模态、Agent 原型、智能 NPC 与内容生成；企业 AI 项目落地是加分项，但需要补游戏业务理解"],
["苏州科达","b2b","大模型应用研发 · AI 业务开发 · 视讯 AI 应用","苏州/上海","无有效 27 届公开码","BYDNTA02 来自 26 春招补录，已过适用期，不建议填","https://kedacom.zhiye.com/Campus","","2027 校招仍可申请","官方页当前仍列大模型应用研发、AI 业务开发和视讯 AI 应用；优先大模型应用研发，和 RAG/Agent 工程经历最贴"],
["北方华创","hw","Agent 开发工程师 J16415","北京","IVB9AK","09-07 员工公开帖提供，来源称可加快筛选，未实测","https://career.naura.com/campus","","2027 校招进行中","国企；硕士、软件工程/计算机相关，岗位名与 Agent 方向直接匹配；投递时按岗位编号 J16415 搜索"],
["中景芯创","hw","AI Agent 开发工程师 · AI 应用工程师","北京/上海","无公开码","未找到可追溯的 27 届公开内推码","https://stics.zhiye.com/campus","","2027 校招进行中","国企；面向 2027 届海内外本硕博，软件工程/人工智能等专业可投；岗位在数字化与 IT 类，需在官网核对具体城市与学历"],
["威迈斯新能源","car","AI Agent 开发工程师 J11836","深圳","无公开码","官方公告仅建议联系员工获取专属内推，未发现可公开核验的码","https://vmax.zhiye.com/campus","2026-10-25","27 届秋招 · 聚合页标至 10-25","接受 2026-09~2027-09 毕业，本科及以上、计算机类可投；岗位名直接匹配 Agent，但具体 JD 仍需登录官网核对"],
["富兰瓦时 FranklinWH","frn","大模型工程师（Agent · Harness · RAG）","深圳","无公开码","未找到可追溯的 27 届公开内推码；不使用招聘联系人私人手机号代替内推码","https://jyb.gzist.edu.cn/info/2022/4565.htm","","2027 届校招进行中","申请条件、岗位状态及历史投递记录请以官方招聘系统和本人情况为准。"],
["虹科","b2b","AI 应用开发工程师","上海/广州","需员工/校园大使提供","官方 2027 简章只说明可向员工或校园大使获取内推码，未找到公开可核验代码","https://job.hkaco.com/recruitment-2/","","2027 届校招进行中","私企；2027 海内外硕士可投。岗位含 LLM API、Prompt、RAG、Python 及应用落地，同时涉及嵌入式部署和模型压缩，需坦诚说明端侧优化经验有限"]
];

// 与上面的每日追加区同步维护，用于页面上的“最近新增”筛选与日期标记。
export const APPEND_DATES = new Map([
  ["途游游戏","2026-09-19"],
  ["苏州科达","2026-09-19"],
  ["北方华创","2026-09-19"],
  ["中景芯创","2026-09-19"],
  ["威迈斯新能源","2026-09-19"],
  ["富兰瓦时 FranklinWH","2026-09-20"],
  ["虹科","2026-09-20"]
]);


export function hasCode(row: CompanyRow): boolean { return /^[A-Za-z0-9]{4,24}$/.test(row[F.code]); }
